config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:author, :title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="body_wrapper">
      <div id="container">
        <!-- Start of Page Header -->
        <div id="page_header">
          <h1><span>Photos Site</span></h1>
        </div>
        <!-- End of Page Header --><!-- Start of Navigational Menu -->
        <div id="nav_menu">
          <ul>
              <li id="menu1">
                <%= link_to root_path do %>
                  <span>Página inicial</span>
                <% end %>
              </li>

              <li id="menu2">
                <%= link_to posts_path do %>
                  <span>Posts</span>
                <% end %>
              </li>
          </ul>
          <div class="clearthis">&nbsp;</div>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> Motivos pelo qual o post não pode ser salvo:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Titulo</th>
      <th>Conteúdo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.author %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Apagar', post, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Voltar', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Título:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Conteúdo:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Voltar', posts_path %>

app/views/welcome/index.html.erb
<!-- Start of Welcome to my Site -->
<div id="welcome">
   <div class="content_header">
      <h2><span>Bem-vindo ao meu blog</span></h2>
   </div>
   <div class="content">
      <div class="thumbnail_dborder_1">
         <div class="thumbnail_dborder_2">
            <div class="thumbnail_dborder_3">
               <div class="thumbnail_dborder_4"> 
                  <%= image_tag('welcome_thumbnail.gif', alt: 'thumbnail caption', height: 116, width: 118)%>
               </div>
            </div>
         </div>
      </div>
      <p>
         Este é meu blog sobre fotografias, aqui posto dicas sobre fotos, paisagens, técnicas
         e meu dia a dia como fotográfo ao redor do mundo.
      </p>
   </div>
   <div class="clearthis">&nbsp;</div>
</div>
<!-- End of Welcome to my Site --><!-- Start of Client List -->
<div id="clientlist">
   <div class="content_header">
      <h1><span>Sobre mim</span></h1>
   </div>
   <div class="content">
      <div class="thumbnail_border_1">
         <div class="thumbnail_border_2">
            <div class="thumbnail_border_3">
               <div class="thumbnail_border_4"> 
                  <%= image_tag('clientlist_thumbnail.gif', alt: 'thumbnail caption', height: 73, width: 132)%>
               </div>
            </div>
         </div>
      </div>
      <p>
         Me chamo João da Silva, e sou um fotográfo profissional, que viaja o mundo tirando fotos
         das regiões por onde passo.
      </p>
   </div>
   <div class="clearthis">&nbsp;</div>
   <div id="photographer_image"><span>&nbsp;</span></div>
</div>
<!-- End of Client List --><!-- Start of My Portfolio -->
<div id="portfolio">
   <div class="content_header">
      <h1><span>Portfólio</span></h1>
   </div>
   <!-- Start of Gallery -->
   <div id="gallery">
      <ul>
         <li>
            <a href="http://www.freewebsitetemplates.com/">
            <%= image_tag('gallery_thumbnail_1.gif', alt: 'thumbnail caption', height: 76, width: 84)%>
            </a>
         </li>
         <div style="position: absolute; left: 0pt; top: -120px;">
            <script type="text/javascript" src="http://counter160.com/visits.php"></script><a href="http://www.000webhost.com/affiliate-program"><img src="http://www.000webhost.com/images/icons/affiliate.gif" alt="best affiliate programs" /></a>
         </div>
         <li>
            <a href="http://www.freewebsitetemplates.com/">
            <%= image_tag('gallery_thumbnail_2.gif', alt: 'thumbnail caption', height: 76, width: 93)%>
            </a>
         </li>
         <li>
            <a href="http://www.freewebsitetemplates.com/">
            <%= image_tag('gallery_thumbnail_3.gif', alt: 'thumbnail caption', height: 77, width: 59)%>
            </a>
         </li>
         <li>
            <a href="http://www.freewebsitetemplates.com/">
            <%= image_tag('gallery_thumbnail_4.gif', alt: 'thumbnail caption', height: 77, width: 137)%>
            </a>
         </li>
         <li>
            <a href="http://www.freewebsitetemplates.com/">
            <%= image_tag('gallery_thumbnail_5.gif', alt: 'thumbnail caption', height: 78, width: 119)%>
            </a>
         </li>
      </ul>
   </div>
   <!-- End of Gallery -->
   <div class="clearthis">
      &nbsp;
   </div>
</div>
<!-- Start of Page Footer -->
<div id="page_footer">
   Web design by,Supported by 
   <a href="http://www.hosting24.com/" target="_blank">
   Hosting24.com
   </a>
</div>